### ISSUE TITLE
Mock FieldValue.increment()

### ISSUE THREAD

**Issue by dmurvihill** [dmurvihill/firebase-mock#15]
Firebase SDK [5.9.0](https://firebase.google.com/support/release-notes/js#version_590_-_mar_14_2019) added this neat new method that we should mock.

**Comment by alexlouden** [comment]
I had a quick play with this today, got it working in my fork: https://github.com/alexlouden/firebase-mock/commit/511da3859632540d895bb646d106302f3a6ec7e8

I did it a bit differently to how `arrayUnion` etc is implemented (I discovered these a bit later on), and haven't written any tests yet, so when/if I have time I'll revisit it and improve it

**Comment by alexlouden** [comment]
Okay I added it properly this time :) See #54 - please let me know if you have any feedback!

**Comment by dmurvihill** [comment]
Thanks! Let's continue the conversation over there.
