### ISSUE TITLE
createUser never returns

### ISSUE THREAD

**Issue by ripperdoc** [dmurvihill/firebase-mock#68]
I have a test that calls a method in my source, that in turn calls Firebase Auth to create a user. But the Promise never resolves, timing out my Mocha test.

Here's the source, simplified:
```
async function addUser(fb, userInput) {
  await fb.auth().createUser(userInput);
}

```
And here is my test, simplified:
```
const firebasemock    = require('firebase-mock');

const mockauth = new firebasemock.MockAuthentication();
const mockdatabase = new firebasemock.MockFirebase();
const mockfirestore = null;
const mockstorage = new firebasemock.MockStorage();
const mockmessaging = null;
const mockfb = new firebasemock.MockFirebaseSdk(
  // use null if your code does not use RTDB
  (path) => {
    return path ? mockdatabase.child(path) : mockdatabase;
  },
  // use null if your code does not use AUTHENTICATION
  () => {
    return mockauth;
  },
  // use null if your code does not use FIRESTORE
  () => {
    return mockfirestore;
  },
  // use null if your code does not use STORAGE
  () => {
    return mockstorage;
  },
  // use null if your code does not use MESSAGING
  () => {
    return mockmessaging;
  }
);

describe('addUser', function () {

    it("createsUser", async () => {
      const testInput = {
        email: "test@test.com"
      }
      await users.addUser(mockfb, testInput);
    });

```
It basically times out waiting for createUser. Should I use flush here somewhere, or what am I doing wrong?

**Comment by lesmo** [comment]
Yes, you're missing a call to `.flush()` because `firebase-mock` also "mocks" async ops. Your requested changes are applied to the in-memory implementation of Firebase, but the async promises are not being fulfilled for that reason.

You can call `mockauth.autoFlush()` before your tests so that every operation is immediately "flushed" as soon as it's called.

**Comment by dmurvihill** [comment]
Closing since this has been answered.
